# Generated by Django 5.2.10 on 2026-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('error', 'error')], default='queued', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('stage', models.CharField(default='queued', max_length=64)),
                ('file_sha256', models.CharField(db_index=True, default='', max_length=64)),
                ('filename', models.CharField(default='', max_length=255)),
                ('result_markdown', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
